FROM python:3.7

EXPOSE 8501

WORKDIR /streamlit

COPY requirements.txt /streamlit
RUN pip install -r requirements.txt

COPY . ./streamlit

EXPOSE 8501

CMD ["streamlit", "run", "streamlit/app.py", "--server.port", "8501"]
