FROM python:3.7

EXPOSE 8501

WORKDIR /mycroft

COPY requirements.txt /mycroft
RUN pip install -r requirements.txt

COPY . ./mycroft

EXPOSE 8501

CMD ["streamlit", "run", "mycroft/app.py", "--server.port", "8501"]
